project_id = "fappyyhsdmybkyrhyutm"

[functions.vault-view]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.pet-care-reminders]
verify_jwt = false

[functions.vaccination-reminders]
verify_jwt = false
